export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const SNACKBAR_SUCCESS = 'SNACKBAR_SUCCESS';
export const SNACKBAR_FAILED = 'SNACKBAR_FAILED';
export const SNACKBAR_CLEAR = 'SNACKBAR_CLEAR';

export const SHOW_MENU_MOBILE = 'SHOW_MENU_MOBILE';
export const HIDE_MENU_MOBILE = 'HIDE_MENU_MOBILE';
export const TOGGLE_MENU_MOBILE = 'TOGGLE_MENU_MOBILE';

export const GET_LIST_REQUEST = 'GET_LIST_REQUEST';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_FAILED = 'GET_LIST_FAILED';

export const GET_ONE_REQUEST = 'GET_ONE_REQUEST';
export const GET_ONE_SUCCESS = 'GET_ONE_SUCCESS';
export const GET_ONE_FAILED = 'GET_ONE_FAILED';